### PR TITLE
fix: type exports v2

### PR DESCRIPTION
**Pull request by dpschen**
Seems like the type exports were still not fully working with my pull request.
Now they do:

image

### CODE REVIEW

**Comment by dpschen** [comment]
@InfectoOne: Do you know when you will be able to check this out?

**Comment by InfectoOne** [comment]
> @InfectoOne: Do you know when you will be able to check this out?

I just checked this out, but I am not able to see the types in VS Code on hover.
Are you using the VS Code extension "Volar" ?

**Comment by dpschen** [comment]
Yes, I use Volar.

The screenshot is from a repo where I used this branch. I built it via NPM pack and then linked it.
Are you referring to the playground? I'm not sure if the types on hover work there since it links to the not yet built version.

**Comment by InfectoOne** [comment]
> Yes, I use Volar.
> 
> The screenshot is from a repo where I used this branch. I built it via NPM pack and then linked it. Are you referring to the playground? I'm not sure if the types on hover work there since it links to the not yet built version.

I am also using the npm-packed version in another test repo and I can't see the types on hover. I will take a further look at this in the following days, then I will merge this, assuming that it's merely a local configuration problem in my environment.

**Comment by dpschen** [comment]
If you have an idea how I could provide a testable environment with the built package I'm also happy to provide that.

**Comment by InfectoOne** [comment]
> If you have an idea how I could provide a testable environment with the built package I'm also happy to provide that.

As expected, it was a local configuration problem. All good, this will be merged soon.

**Pull request merged**
